selection.fore=#ff0000
selection.additional.fore=#ff0000
selection.inactive.fore=#ff0000
selection.layer=2
if PLAT_WINNT
	selection.back=#00000020
if PLAT_GTK
	selection.back=#0000001E
	selection.secondary.back=#00800010
if PLAT_MAC
	selection.back=#00000020
selection.additional.back=#00000010
selection.inactive.back=#00000010
check.if.already.open=1
find.close.on.find=0
